### PR TITLE
use color and style of edges to indicate dependency types

### PR DESCRIPTION
**Pull request by dirk-thomas**
Using different colors based on the dependency type provide more information in the graph. Also when selecting only some packages showing indirect dependencies avoids missing those when looking at a subgraph.

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
Looks nice!

For some reason the behavior is not deterministic though.
Is there a priority between build depends and run depends deciding what the end color of the arrow will be?

Command I ran for testing:
```
colcon list --packages-above rclcpp --topological-graph-dot  | dot -Tpng -o graph.png
```

First result (what I expected): 
image

Second run:
image

**Comment by dirk-thomas** [comment]
I updated the code to not rely on the order of the collections (only the case in CPython 3.6+, Python 3.7+). It also renders multiple parallel dependency types as separate edged.

The packages matching `rcl.*`: 
rcl-star

The packages matching `rcl.+`: 
rcl-plus

**Comment by mikaelarguedas** [comment]
Looks better and is deterministic now :+1:

Some edges have funny shapes though (rviz2 to rclcpp on the following graph for example)
image
Just a remark not that there is anything to do about it

Very useful tool, just by printing a few random graphs we can already see "surprising" relationships between packages

**Comment by dirk-thomas** [comment]
> We could gain in readability by being slightly less conservative in variable shortening. e.g. cat -> category

Absolutely, before the line length was getting too long so I shortened it to `cat`. But with the ongoing change that is not the case anymore so I "expanded" it back to `category`: 46343c48b45ed2e3a19bba0f737abaaac585a0f5

**Pull request merged**
